version: 2

jobs:
  build:
    docker:
      - image: elixir:1.11.2-slim
        environment:
          MIX_ENV: test
          DB_PASSWORD: postgres
          DB_USER: postgres
          DB_NAME: blog_api_db_test      
          DB_HOST: db

      - image: postgres:11-alpine        
        name: db
        restart: always
        environment:
          PGDATA: /var/lib/postgresql/data/pgdata
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: blog_api_db_test
        
    working_directory: ~/repo
    steps:
      - checkout

      - run: apt-get update && apt-get install make gcc -y && mix do local.hex --force, local.rebar
      - run: mix setup
      - run: mix test                
